//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Availability
    {
        public int Id { get; set; }
        public Nullable<int> IdDrugs { get; set; }
        public Nullable<int> IdPharmacy { get; set; }
        public string Value { get; set; }
        public string Price { get; set; }
    
        public virtual Drugs Drugs { get; set; }
        public virtual Pharmacy Pharmacy { get; set; }
    }
}
